server:
  port: 8889
spring:
  cloud:
    config:
      server:
        git:
          uri: file://C:/LessonLearned/workspace/configuration-service/
          username: dg-mihlo
          password: start123
          force-pull: true