server:
  port: 8889
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dg-mihlo/lesson_learned/
          username: dg-mihlo
          password: start123
          force-pull: true