server:
	port: 8888
spring:
	cloud:
		config:
            label: master
			server:
				git:
					uri: https://github.com/dg-mihlo/lesson_learned/configuration-service.git
					username: dg-mihlo
					password: $%bIkE(Int17)